


export interface SalleMusculationAPI {
    "inst_numero":string,
    "inst_nom": string;
    "inst_adresse": string;
    "inst_cp": string;
    "inst_com_code": string;
    "inst_com_nom": string;
    "new_code": string;
    "new_name": string;
    "inst_actif": string;
    "inst_etat": string;
    "inst_date_creation": string;
    "inst_date_etat": string;
    "inst_date_valid": string;
    "inst_acc_handi_bool": string;
    "inst_enqu_date": string;
    "inst_obs": string;
    "inst_trans_bool": string;
    "inst_part_bool": string;
    "inst_part_type": string;
    "inst_part_type_filter": string;
    "inst_acc_handi_type": string;
    "inst_trans_type": string;
    "inst_siret": string;
    "inst_uai": string;
    "inst_hs_bool": string;
    "equip_numero": string;
    "equip_nom": string;
    "equip_type_code": string;
    "equip_type_name": string;
    "equip_type_famille": string;
    "coordonnees":string[];

    "equip_etat": string;
    "equip_x": string;
    "equip_y": string;
    "equip_eclair": string;
    "equip_acc_libre": string;
    "equip_conf_bool": string;
    "equip_ouv_public_bool":string;
    "equip_loc_bool": string;
    "equip_saison": string;
    "equip_douche": string;
    "equip_sanit": string;
    "equip_dsp": string;
    "equip_pmr_acc":string;
    "equip_pmr_aire": string;
    "equip_pmr_chem": string;
    "equip_pmr_douche":string;
    "equip_pmr_sanit": string;
    "equip_pmr_trib": string;string;
    "equip_pmr_vest": string;
    "equip_pshs_aire": string;
    "equip_pshs_chem": string;
    "equip_pshs_sanit":string;
    "equip_pshs_sign": string;
    "equip_pshs_trib": string;estring;
    "equip_pshs_vest": string;
    "equip_homo_date": string;
    "equip_travaux_date":string;
    "equip_erp_cat": string;
    "equip_haut": string;
    "equip_larg": string;
    "equip_long":string;
    "equip_surf": string;
    "equip_piste_nb": string;
    "equip_trib_nb": string;
    "equip_vest_ens":string;
    "equip_vest_sport":string;
    "equip_sae_couloir":string;
    "equip_sae_haut": string;
    "equip_sae_surf": string;
    "equip_bassin_long": string;
    "equip_bassin_larg": string;
    "equip_bassin_surf": string;
    "equip_bassin_min": string;
    "equip_bassin_max": string;
    "equip_piste_long": string;
    "equip_url": string;
    "equip_service_date": string;
    "equip_prop_nom": string;
    "equip_obs": string;
    "equip_decl_nom": string;
    "equip_decl_prenom": string;
    "equip_decl_mail": string;
    "equip_decl_adresse": string;
    "equip_decl_cp": string;
    "equip_decl_commune": string;
    "equip_redac_commune": string;
    "equip_redac_date": string;
    "equip_conf_type": string;
    "equip_erp_type": string;
    "equip_loc_type": string;
    "equip_travaux_type": string;
    "equip_energie": string;
    "equip_utilisateur": string;
    "equip_pasdetir": string;
    "equip_sol": string;
    "equip_nature": string;
    "equip_service_periode": string;
    "equip_homo_periode": string;
    "equip_travaux_periode": string;
    "equip_decl_type": string;
    "equip_prop_type": string;
    "equip_propsec_type": string;
    "equip_gest_type": string;
    "equip_cogest_type": string;
    "equip_pdesi_pdipr": string;
    "equip_decl_tel": string;
    "equip_rnb": string;
    "equip_aps_code": string;
    "equip_aps_nom": string;
    "equip_aps_json": string;
    "epci_code": string;
    "epci_nom": string;
    "code_bdv": string;
    "lib_bdv": string;
    "arr_code": string;
    "arr_name": string;
    "dep_code": string;
    "dep_code_filled": string;
    "dep_nom": string;
    "aca_nom": string;
    "reg_code": string;
    "reg_nom": string;
    "dens_niveau": string;
    "dens_lib": string;
    "zrr_simp": string;
    "rnb_id": string;
    "categorie":string;
}
